In [102]:
import pandas as pd
import numpy as np

In [103]:
file1 = pd.read_csv("D:\IPL_WinPrediction\IPL_Dataset_Clean.csv")
file1

,ID,Team1,Team2,City,TossWinner,WonBy,TossDecision,WinningTeam,T1_P1,T1_P2,...,T2_P2,T2_P3,T2_P4,T2_P5,T2_P6,T2_P7,T2_P8,T2_P9,T2_P10,T2_P11
0,1312200,Rajasthan Royals,Gujarat Titans,Ahmedabad,Rajasthan Royals,Wickets,bat,Gujarat Titans,YBK Jaiswal,JC Buttler,...,Shubman Gill,MS Wade,HH Pandya,DA Miller,R Tewatia,Rashid Khan,R Sai Kishore,LH Ferguson,Yash Dayal,Mohammed Shami
1,1312199,Royal Challengers Bangalore,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Wickets,field,Rajasthan Royals,V Kohli,F du Plessis,...,JC Buttler,SV Samson,D Padikkal,SO Hetmyer,R Parag,R Ashwin,TA Boult,YS Chahal,M Prasidh Krishna,OC McCoy
2,1312198,Royal Challengers Bangalore,Lucknow Super Giants,Kolkata,Lucknow Super Giants,Runs,field,Royal Challengers Bangalore,V Kohli,F du Plessis,...,KL Rahul,M Vohra,DJ Hooda,MP Stoinis,E Lewis,KH Pandya,PVD Chameera,Mohsin Khan,Avesh Khan,Ravi Bishnoi
3,1312197,Rajasthan Royals,Gujarat Titans,Kolkata,Gujarat Titans,Wickets,field,Gujarat Titans,YBK Jaiswal,JC Buttler,...,Shubman Gill,MS Wade,HH Pandya,DA Miller,R Tewatia,Rashid Khan,R Sai Kishore,AS Joseph,Yash Dayal,Mohammed Shami
4,1304116,Sunrisers Hyderabad,Punjab Kings,Mumbai,Sunrisers Hyderabad,Wickets,bat,Punjab Kings,PK Garg,Abhishek Sharma,...,S Dhawan,M Shahrukh Khan,MA Agarwal,LS Livingstone,JM Sharma,PN Mankad,Harpreet Brar,K Rabada,NT Ellis,Arshdeep Singh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941,335986,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,Sunrisers Hyderabad,Wickets,bat,Kolkata Knight Riders,R Dravid,W Jaffer,...,BB McCullum,RT Ponting,DJ Hussey,Mohammad Hafeez,LR Shukla,WP Saha,AB Agarkar,AB Dinda,M Kartik,I Sharma
942,335985,Mumbai Indians,Royal Challengers Bangalore,Mumbai,Mumbai Indians,Wickets,bat,Royal Challengers Bangalore,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
943,335984,Delhi Capitals,Rajasthan Royals,Delhi,Rajasthan Royals,Wickets,bat,Delhi Capitals,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
944,335983,Punjab Kings,Chennai Super Kings,Chandigarh,Chennai Super Kings,Runs,bat,Chennai Super Kings,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
945,335982,Royal Challengers Bangalore,Kolkata Knight Riders,Bangalore,Royal Challengers Bangalore,Runs,field,Kolkata Knight Riders,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [104]:
file2 = pd.read_csv("D:\IPL_WinPrediction\IPL_Ball_by_Ball_2008_2022.csv")
file2

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225950,335982,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225951,335982,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225952,335982,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225953,335982,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore

In [105]:
file1.dropna(inplace=True)

In [106]:
file1.isnull().sum()

ID              0
Team1           0
Team2           0
City            0
TossWinner      0
WonBy           0
TossDecision    0
WinningTeam     0
T1_P1           0
T1_P2           0
T1_P3           0
T1_P4           0
T1_P5           0
T1_P6           0
T1_P7           0
T1_P8           0
T1_P9           0
T1_P10          0
T1_P11          0
T2_P1           0
T2_P2           0
T2_P3           0
T2_P4           0
T2_P5           0
T2_P6           0
T2_P7           0
T2_P8           0
T2_P9           0
T2_P10          0
T2_P11          0
dtype: int64

In [107]:
IPL_Data =file1.copy()

In [108]:
IPL_Data

,ID,Team1,Team2,City,TossWinner,WonBy,TossDecision,WinningTeam,T1_P1,T1_P2,...,T2_P2,T2_P3,T2_P4,T2_P5,T2_P6,T2_P7,T2_P8,T2_P9,T2_P10,T2_P11
0,1312200,Rajasthan Royals,Gujarat Titans,Ahmedabad,Rajasthan Royals,Wickets,bat,Gujarat Titans,YBK Jaiswal,JC Buttler,...,Shubman Gill,MS Wade,HH Pandya,DA Miller,R Tewatia,Rashid Khan,R Sai Kishore,LH Ferguson,Yash Dayal,Mohammed Shami
1,1312199,Royal Challengers Bangalore,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Wickets,field,Rajasthan Royals,V Kohli,F du Plessis,...,JC Buttler,SV Samson,D Padikkal,SO Hetmyer,R Parag,R Ashwin,TA Boult,YS Chahal,M Prasidh Krishna,OC McCoy
2,1312198,Royal Challengers Bangalore,Lucknow Super Giants,Kolkata,Lucknow Super Giants,Runs,field,Royal Challengers Bangalore,V Kohli,F du Plessis,...,KL Rahul,M Vohra,DJ Hooda,MP Stoinis,E Lewis,KH Pandya,PVD Chameera,Mohsin Khan,Avesh Khan,Ravi Bishnoi
3,1312197,Rajasthan Royals,Gujarat Titans,Kolkata,Gujarat Titans,Wickets,field,Gujarat Titans,YBK Jaiswal,JC Buttler,...,Shubman Gill,MS Wade,HH Pandya,DA Miller,R Tewatia,Rashid Khan,R Sai Kishore,AS Joseph,Yash Dayal,Mohammed Shami
4,1304116,Sunrisers Hyderabad,Punjab Kings,Mumbai,Sunrisers Hyderabad,Wickets,bat,Punjab Kings,PK Garg,Abhishek Sharma,...,S Dhawan,M Shahrukh Khan,MA Agarwal,LS Livingstone,JM Sharma,PN Mankad,Harpreet Brar,K Rabada,NT Ellis,Arshdeep Singh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,335990,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,Rajasthan Royals,Wickets,field,Rajasthan Royals,WP Saha,BB McCullum,...,Y Venugopal Rao,VVS Laxman,A Symonds,RG Sharma,SB Styris,AS Yadav,SB Bangar,WPUJC Vaas,RP Singh,PP Ojha
938,335989,Chennai Super Kings,Mumbai Indians,Chennai,Mumbai Indians,Runs,field,Chennai Super Kings,L Ronchi,ST Jayasuriya,...,R Dravid,LRPL Taylor,JH Kallis,V Kohli,MV Boucher,B Akhil,P Kumar,Z Khan,SB Joshi,R Vinay Kumar
939,335988,Sunrisers Hyderabad,Delhi Capitals,Hyderabad,Sunrisers Hyderabad,Wickets,bat,Delhi Capitals,G Gambhir,V Sehwag,...,YK Pathan,SR Watson,M Kaif,DS Lehmann,RA Jadeja,M Rawat,D Salunkhe,SK Warne,SK Trivedi,MM Patel
940,335987,Rajasthan Royals,Punjab Kings,Jaipur,Punjab Kings,Wickets,bat,Rajasthan Royals,K Goel,JR Hopes,...,ML Hayden,MEK Hussey,MS Dhoni,SK Raina,JDP Oram,S Badrinath,Joginder Sharma,P Amarnath,MS Gony,M Muralitharan
941,335986,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,Sunrisers Hyderabad,Wickets,bat,Kolkata Knight Riders,R Dravid,W Jaffer,...,BB McCullum,RT Ponting,DJ Hussey,Mohammad Hafeez,LR Shukla,WP Saha,AB Agarkar,AB Dinda,M Kartik,I Sharma

In [109]:
file3 = pd.read_csv("D:\IPL_WinPrediction\IPL_PlayerPerformance.csv")

In [110]:
file3

,Player,BattingAverage,Strike Rate,Runs Conceded,Wickets,BowlingAverage,Economy Rate
0,A Ashish Reddy,12.173913,142.857143,400.0,18.0,22.222222,8.888889
1,A Badoni,14.636364,115.827338,12.0,2.0,6.000000,6.000000
2,A Chandila,2.000000,57.142857,245.0,11.0,22.272727,6.282051
3,A Chopra,8.833333,70.666667,0.0,0.0,0.000000,0.000000
4,A Choudhary,8.333333,125.000000,144.0,5.0,28.800000,8.000000
...,...,...,...,...,...,...,...
647,Yash Dayal,0.000000,0.000000,296.0,11.0,26.909091,8.663415
648,Yashpal Singh,11.750000,70.149254,0.0,0.0,0.000000,0.000000
649,Younis Khan,3.000000,42.857143,0.0,0.0,0.000000,0.000000
650,Yuvraj Singh,21.857143,124.784776,1091.0,36.0,30.305556,7.421769
651,Z Khan,4.333333,82.978723,2860.0,103.0,27.766990,7.539543

In [111]:
T1_P_columns = [f'T1_P{i}' for i in range(1, 12)]

In [112]:
for player_column in T1_P_columns:
    IPL_Data = pd.merge(IPL_Data, file3[['Player','BattingAverage','BowlingAverage','Strike Rate']], left_on=player_column, right_on='Player', how='left')
    IPL_Data.drop(['Player', player_column], axis=1, inplace=True)
    IPL_Data.rename(
        {
            'BattingAverage': f'{player_column}BattingAverage',
            'BowlingAverage': f'{player_column}BowlingAverage',
            'Strike Rate': f'{player_column}StrikeRate',
        },
        axis=1,
        inplace=True
    )

In [113]:
IPL_Data

,ID,Team1,Team2,City,TossWinner,WonBy,TossDecision,WinningTeam,T2_P1,T2_P2,...,T1_P8StrikeRate,T1_P9BattingAverage,T1_P9BowlingAverage,T1_P9StrikeRate,T1_P10BattingAverage,T1_P10BowlingAverage,T1_P10StrikeRate,T1_P11BattingAverage,T1_P11BowlingAverage,T1_P11StrikeRate
0,1312200,Rajasthan Royals,Gujarat Titans,Ahmedabad,Rajasthan Royals,Wickets,bat,Gujarat Titans,WP Saha,Shubman Gill,...,108.163265,8.000000,22.000000,160.000000,1.285714,34.820000,37.500000,2.176471,22.283133,41.573034
1,1312199,Royal Challengers Bangalore,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Wickets,field,Rajasthan Royals,YBK Jaiswal,JC Buttler,...,78.000000,7.419355,23.319588,121.693122,3.600000,23.562500,66.666667,5.647059,33.200000,86.486486
2,1312198,Royal Challengers Bangalore,Lucknow Super Giants,Kolkata,Lucknow Super Giants,Runs,field,Royal Challengers Bangalore,Q de Kock,KL Rahul,...,121.693122,4.333333,19.192308,78.000000,3.600000,23.562500,66.666667,5.647059,33.200000,86.486486
3,1312197,Rajasthan Royals,Gujarat Titans,Kolkata,Gujarat Titans,Wickets,field,Gujarat Titans,WP Saha,Shubman Gill,...,108.163265,2.176471,22.283133,41.573034,1.285714,34.820000,37.500000,8.000000,22.000000,160.000000
4,1304116,Sunrisers Hyderabad,Punjab Kings,Mumbai,Sunrisers Hyderabad,Wickets,bat,Punjab Kings,JM Bairstow,S Dhawan,...,112.903226,4.381818,26.389610,93.050193,1.000000,22.958333,50.000000,2.000000,55.000000,25.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,335990,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,Rajasthan Royals,Wickets,field,Rajasthan Royals,AC Gilchrist,Y Venugopal Rao,...,111.875000,1.625000,30.478261,52.000000,8.071429,45.741935,103.669725,3.055556,38.597222,88.709677
938,335989,Chennai Super Kings,Mumbai Indians,Chennai,Mumbai Indians,Runs,field,Chennai Super Kings,S Chanderpaul,R Dravid,...,130.974843,8.000000,26.000000,109.090909,2.411765,23.933962,65.079365,5.200000,29.220930,92.035398
939,335988,Sunrisers Hyderabad,Delhi Capitals,Hyderabad,Sunrisers Hyderabad,Wickets,bat,Delhi Capitals,T Kohli,YK Pathan,...,102.542373,12.642857,19.703704,142.741935,0.000000,91.000000,0.000000,2.000000,30.500000,80.000000
940,335987,Rajasthan Royals,Punjab Kings,Jaipur,Punjab Kings,Wickets,bat,Rajasthan Royals,PA Patel,ML Hayden,...,121.568627,7.684211,27.821656,107.550645,7.000000,24.500000,73.684211,2.833333,29.780488,59.649123
941,335986,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,Sunrisers Hyderabad,Wickets,bat,Kolkata Knight Riders,SC Ganguly,BB McCullum,...,75.000000,5.964912,37.133333,105.263158,4.333333,27.766990,82.978723,3.000000,82.000000,37.500000

In [114]:
T2_P_columns = [f'T2_P{i}' for i in range(1, 12)]

In [115]:
for player_column in T2_P_columns:
    IPL_Data = pd.merge(IPL_Data, file3[['Player','BattingAverage','BowlingAverage','Strike Rate']], left_on=player_column, right_on='Player', how='left')
    IPL_Data.drop(['Player', player_column], axis=1, inplace=True)
    IPL_Data.rename(
        {
            'BattingAverage': f'{player_column}BattingAverage',
            'BowlingAverage': f'{player_column}BowlingAverage',
            'Strike Rate': f'{player_column}StrikeRate',
        },
        axis=1,
        inplace=True
    )

In [116]:
IPL_Data.fillna(value=0,inplace=True)

In [117]:
IPL_Data['Team1BattingAverage'] = (IPL_Data['T1_P1BattingAverage'] + IPL_Data['T1_P2BattingAverage'] + IPL_Data['T1_P3BattingAverage'] + IPL_Data['T1_P4BattingAverage'] + IPL_Data['T1_P5BattingAverage'] + IPL_Data['T1_P6BattingAverage'] + IPL_Data['T1_P7BattingAverage'] + IPL_Data['T1_P8BattingAverage'] + IPL_Data['T1_P9BattingAverage'] + IPL_Data['T1_P10BattingAverage'] + IPL_Data['T1_P11BattingAverage'])/11
IPL_Data['Team2BattingAverage'] = (IPL_Data['T2_P1BattingAverage'] + IPL_Data['T2_P2BattingAverage'] + IPL_Data['T2_P3BattingAverage'] + IPL_Data['T2_P4BattingAverage'] + IPL_Data['T2_P5BattingAverage'] + IPL_Data['T2_P6BattingAverage'] + IPL_Data['T2_P7BattingAverage'] + IPL_Data['T2_P8BattingAverage'] + IPL_Data['T2_P9BattingAverage'] + IPL_Data['T2_P10BattingAverage'] + IPL_Data['T2_P11BattingAverage'])/11

In [118]:
IPL_Data['Team1BowlingAverage'] = (IPL_Data['T1_P1BowlingAverage'] + IPL_Data['T1_P2BowlingAverage'] + IPL_Data['T1_P3BowlingAverage'] + IPL_Data['T1_P4BowlingAverage'] + IPL_Data['T1_P5BowlingAverage'] + IPL_Data['T1_P6BowlingAverage'] + IPL_Data['T1_P7BowlingAverage'] + IPL_Data['T1_P8BowlingAverage'] + IPL_Data['T1_P9BowlingAverage'] + IPL_Data['T1_P10BowlingAverage'] + IPL_Data['T1_P11BowlingAverage'])/11
IPL_Data['Team2BowlingAverage'] = (IPL_Data['T2_P1BowlingAverage'] + IPL_Data['T2_P2BowlingAverage'] + IPL_Data['T2_P3BowlingAverage'] + IPL_Data['T2_P4BowlingAverage'] + IPL_Data['T2_P5BowlingAverage'] + IPL_Data['T2_P6BowlingAverage'] + IPL_Data['T2_P7BowlingAverage'] + IPL_Data['T2_P8BowlingAverage'] + IPL_Data['T2_P9BowlingAverage'] + IPL_Data['T2_P10BowlingAverage'] + IPL_Data['T2_P11BowlingAverage'])/11

In [119]:
IPL_Data['Team1StrikeRate'] = (IPL_Data['T1_P1StrikeRate'] + IPL_Data['T1_P2StrikeRate'] + IPL_Data['T1_P3StrikeRate'] + IPL_Data['T1_P4StrikeRate'] + IPL_Data['T1_P5StrikeRate'] + IPL_Data['T1_P6StrikeRate'] + IPL_Data['T1_P7StrikeRate'] + IPL_Data['T1_P8StrikeRate'] + IPL_Data['T1_P9StrikeRate'] + IPL_Data['T1_P10StrikeRate'] + IPL_Data['T1_P11StrikeRate'])/11
IPL_Data['Team2StrikeRate'] = (IPL_Data['T2_P1StrikeRate'] + IPL_Data['T2_P2StrikeRate'] + IPL_Data['T2_P3StrikeRate'] + IPL_Data['T2_P4StrikeRate'] + IPL_Data['T2_P5StrikeRate'] + IPL_Data['T2_P6StrikeRate'] + IPL_Data['T2_P7StrikeRate'] + IPL_Data['T2_P8StrikeRate'] + IPL_Data['T2_P9StrikeRate'] + IPL_Data['T2_P10StrikeRate'] + IPL_Data['T2_P11StrikeRate'])/11

In [120]:
IPL_Data

,ID,Team1,Team2,City,TossWinner,WonBy,TossDecision,WinningTeam,T1_P1BattingAverage,T1_P1BowlingAverage,...,T2_P10StrikeRate,T2_P11BattingAverage,T2_P11BowlingAverage,T2_P11StrikeRate,Team1BattingAverage,Team2BattingAverage,Team1BowlingAverage,Team2BowlingAverage,Team1StrikeRate,Team2StrikeRate
0,1312200,Rajasthan Royals,Gujarat Titans,Ahmedabad,Rajasthan Royals,Wickets,bat,Gujarat Titans,23.782609,0.00,...,0.000000,3.285714,29.838384,93.243243,15.483259,13.073874,18.708187,17.462245,114.139024,102.594500
1,1312199,Royal Challengers Bangalore,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Wickets,field,Rajasthan Royals,30.855814,92.75,...,37.500000,8.000000,22.000000,160.000000,17.775218,15.483259,32.692278,18.708187,114.000531,114.139024
2,1312198,Royal Challengers Bangalore,Lucknow Super Giants,Kolkata,Lucknow Super Giants,Runs,field,Royal Challengers Bangalore,30.855814,92.75,...,163.157895,2.000000,29.270270,44.444444,17.775218,17.073565,32.692278,20.732313,114.000531,125.011089
3,1312197,Rajasthan Royals,Gujarat Titans,Kolkata,Gujarat Titans,Wickets,field,Gujarat Titans,23.782609,0.00,...,0.000000,3.285714,29.838384,93.243243,15.483259,12.513268,18.708187,17.350909,114.139024,98.726028
4,1304116,Sunrisers Hyderabad,Punjab Kings,Mumbai,Sunrisers Hyderabad,Wickets,bat,Punjab Kings,14.764706,0.00,...,94.736842,2.555556,27.150000,63.888889,13.963378,16.370308,29.160466,16.357071,107.851106,143.763969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,335990,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,Rajasthan Royals,Wickets,field,Rajasthan Royals,20.743590,0.00,...,66.666667,0.842105,26.955056,35.555556,13.275058,13.718252,28.996228,25.987833,99.015413,101.871647
938,335989,Chennai Super Kings,Mumbai Indians,Chennai,Mumbai Indians,Runs,field,Chennai Super Kings,6.800000,0.00,...,37.500000,7.380952,28.961905,107.266436,12.219282,14.072797,19.462522,31.430482,105.212140,102.848265
939,335988,Sunrisers Hyderabad,Delhi Capitals,Hyderabad,Sunrisers Hyderabad,Wickets,bat,Delhi Capitals,27.927152,0.00,...,68.852459,3.250000,23.418919,95.121951,15.381031,10.775962,31.133237,23.123320,107.582916,101.354460
940,335987,Rajasthan Royals,Punjab Kings,Jaipur,Punjab Kings,Wickets,bat,Rajasthan Royals,13.625000,0.00,...,130.263158,2.222222,27.578125,66.666667,12.928698,17.219262,21.043460,19.860622,97.513791,105.548630
941,335986,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,Sunrisers Hyderabad,Wickets,bat,Kolkata Knight Riders,26.512195,0.00,...,103.669725,3.055556,38.597222,88.709677,15.189175,13.275058,40.343036,28.996228,102.678496,99.015413

In [121]:
IPL_Final_Data = IPL_Data[['ID','Team1','Team2','City','TossWinner','TossDecision','WinningTeam','Team1BattingAverage','Team2BattingAverage','Team1BowlingAverage','Team2BowlingAverage','Team1StrikeRate','Team2StrikeRate']].copy()
IPL_Final_Data

,ID,Team1,Team2,City,TossWinner,TossDecision,WinningTeam,Team1BattingAverage,Team2BattingAverage,Team1BowlingAverage,Team2BowlingAverage,Team1StrikeRate,Team2StrikeRate
0,1312200,Rajasthan Royals,Gujarat Titans,Ahmedabad,Rajasthan Royals,bat,Gujarat Titans,15.483259,13.073874,18.708187,17.462245,114.139024,102.594500
1,1312199,Royal Challengers Bangalore,Rajasthan Royals,Ahmedabad,Rajasthan Royals,field,Rajasthan Royals,17.775218,15.483259,32.692278,18.708187,114.000531,114.139024
2,1312198,Royal Challengers Bangalore,Lucknow Super Giants,Kolkata,Lucknow Super Giants,field,Royal Challengers Bangalore,17.775218,17.073565,32.692278,20.732313,114.000531,125.011089
3,1312197,Rajasthan Royals,Gujarat Titans,Kolkata,Gujarat Titans,field,Gujarat Titans,15.483259,12.513268,18.708187,17.350909,114.139024,98.726028
4,1304116,Sunrisers Hyderabad,Punjab Kings,Mumbai,Sunrisers Hyderabad,bat,Punjab Kings,13.963378,16.370308,29.160466,16.357071,107.851106,143.763969
...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,335990,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,Rajasthan Royals,field,Rajasthan Royals,13.275058,13.718252,28.996228,25.987833,99.015413,101.871647
938,335989,Chennai Super Kings,Mumbai Indians,Chennai,Mumbai Indians,field,Chennai Super Kings,12.219282,14.072797,19.462522,31.430482,105.212140,102.848265
939,335988,Sunrisers Hyderabad,Delhi Capitals,Hyderabad,Sunrisers Hyderabad,bat,Delhi Capitals,15.381031,10.775962,31.133237,23.123320,107.582916,101.354460
940,335987,Rajasthan Royals,Punjab Kings,Jaipur,Punjab Kings,bat,Rajasthan Royals,12.928698,17.219262,21.043460,19.860622,97.513791,105.548630
941,335986,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,Sunrisers Hyderabad,bat,Kolkata Knight Riders,15.189175,13.275058,40.343036,28.996228,102.678496,99.015413

In [122]:
IPL_Final_Data.isnull().sum()

ID                     0
Team1                  0
Team2                  0
City                   0
TossWinner             0
TossDecision           0
WinningTeam            0
Team1BattingAverage    0
Team2BattingAverage    0
Team1BowlingAverage    0
Team2BowlingAverage    0
Team1StrikeRate        0
Team2StrikeRate        0
dtype: int64

In [123]:
file4 = pd.read_csv("D:\IPL_WinPrediction\IPL_TeamPerformance.csv")
file4

    TeamID                         Team HomeGround  WinningPercentage
0        1          Chennai Super Kings    Chennai              58.41
1        2               Delhi Capitals      Delhi              45.94
2        3               Gujarat Titans  Ahmedabad              75.00
3        4        Kolkata Knight Riders    Kolkata              51.56
4        5         Lucknow Super Giants    Lucknow              60.00
5        6               Mumbai Indians     Mumbai              56.70
6        7                 Punjab Kings     Punjab              45.87
7        8             Rajasthan Royals     Jaipur              50.26
8        9  Royal Challengers Bangalore  Bangalore              48.65
9       10          Sunrisers Hyderabad  Hyderabad              50.00
10      11         Kochi Tuskers Kerala     Indore              51.12
11      12                Pune Warriors       Pune              36.00

In [124]:
IPL_Final_Data = pd.merge(IPL_Final_Data,file4[['Team','HomeGround','WinningPercentage']],left_on='Team1',right_on='Team',how='left')
IPL_Final_Data

,ID,Team1,Team2,City,TossWinner,TossDecision,WinningTeam,Team1BattingAverage,Team2BattingAverage,Team1BowlingAverage,Team2BowlingAverage,Team1StrikeRate,Team2StrikeRate,Team,HomeGround,WinningPercentage
0,1312200,Rajasthan Royals,Gujarat Titans,Ahmedabad,Rajasthan Royals,bat,Gujarat Titans,15.483259,13.073874,18.708187,17.462245,114.139024,102.594500,Rajasthan Royals,Jaipur,50.26
1,1312199,Royal Challengers Bangalore,Rajasthan Royals,Ahmedabad,Rajasthan Royals,field,Rajasthan Royals,17.775218,15.483259,32.692278,18.708187,114.000531,114.139024,Royal Challengers Bangalore,Bangalore,48.65
2,1312198,Royal Challengers Bangalore,Lucknow Super Giants,Kolkata,Lucknow Super Giants,field,Royal Challengers Bangalore,17.775218,17.073565,32.692278,20.732313,114.000531,125.011089,Royal Challengers Bangalore,Bangalore,48.65
3,1312197,Rajasthan Royals,Gujarat Titans,Kolkata,Gujarat Titans,field,Gujarat Titans,15.483259,12.513268,18.708187,17.350909,114.139024,98.726028,Rajasthan Royals,Jaipur,50.26
4,1304116,Sunrisers Hyderabad,Punjab Kings,Mumbai,Sunrisers Hyderabad,bat,Punjab Kings,13.963378,16.370308,29.160466,16.357071,107.851106,143.763969,Sunrisers Hyderabad,Hyderabad,50.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,335990,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,Rajasthan Royals,field,Rajasthan Royals,13.275058,13.718252,28.996228,25.987833,99.015413,101.871647,Sunrisers Hyderabad,Hyderabad,50.00
938,335989,Chennai Super Kings,Mumbai Indians,Chennai,Mumbai Indians,field,Chennai Super Kings,12.219282,14.072797,19.462522,31.430482,105.212140,102.848265,Chennai Super Kings,Chennai,58.41
939,335988,Sunrisers Hyderabad,Delhi Capitals,Hyderabad,Sunrisers Hyderabad,bat,Delhi Capitals,15.381031,10.775962,31.133237,23.123320,107.582916,101.354460,Sunrisers Hyderabad,Hyderabad,50.00
940,335987,Rajasthan Royals,Punjab Kings,Jaipur,Punjab Kings,bat,Rajasthan Royals,12.928698,17.219262,21.043460,19.860622,97.513791,105.548630,Rajasthan Royals,Jaipur,50.26
941,335986,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,Sunrisers Hyderabad,bat,Kolkata Knight Riders,15.189175,13.275058,40.343036,28.996228,102.678496,99.015413,Kolkata Knight Riders,Kolkata,51.56

In [125]:
IPL_Final_Data.drop(['Team'],axis=1,inplace=True)
IPL_Final_Data

,ID,Team1,Team2,City,TossWinner,TossDecision,WinningTeam,Team1BattingAverage,Team2BattingAverage,Team1BowlingAverage,Team2BowlingAverage,Team1StrikeRate,Team2StrikeRate,HomeGround,WinningPercentage
0,1312200,Rajasthan Royals,Gujarat Titans,Ahmedabad,Rajasthan Royals,bat,Gujarat Titans,15.483259,13.073874,18.708187,17.462245,114.139024,102.594500,Jaipur,50.26
1,1312199,Royal Challengers Bangalore,Rajasthan Royals,Ahmedabad,Rajasthan Royals,field,Rajasthan Royals,17.775218,15.483259,32.692278,18.708187,114.000531,114.139024,Bangalore,48.65
2,1312198,Royal Challengers Bangalore,Lucknow Super Giants,Kolkata,Lucknow Super Giants,field,Royal Challengers Bangalore,17.775218,17.073565,32.692278,20.732313,114.000531,125.011089,Bangalore,48.65
3,1312197,Rajasthan Royals,Gujarat Titans,Kolkata,Gujarat Titans,field,Gujarat Titans,15.483259,12.513268,18.708187,17.350909,114.139024,98.726028,Jaipur,50.26
4,1304116,Sunrisers Hyderabad,Punjab Kings,Mumbai,Sunrisers Hyderabad,bat,Punjab Kings,13.963378,16.370308,29.160466,16.357071,107.851106,143.763969,Hyderabad,50.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,335990,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,Rajasthan Royals,field,Rajasthan Royals,13.275058,13.718252,28.996228,25.987833,99.015413,101.871647,Hyderabad,50.00
938,335989,Chennai Super Kings,Mumbai Indians,Chennai,Mumbai Indians,field,Chennai Super Kings,12.219282,14.072797,19.462522,31.430482,105.212140,102.848265,Chennai,58.41
939,335988,Sunrisers Hyderabad,Delhi Capitals,Hyderabad,Sunrisers Hyderabad,bat,Delhi Capitals,15.381031,10.775962,31.133237,23.123320,107.582916,101.354460,Hyderabad,50.00
940,335987,Rajasthan Royals,Punjab Kings,Jaipur,Punjab Kings,bat,Rajasthan Royals,12.928698,17.219262,21.043460,19.860622,97.513791,105.548630,Jaipur,50.26
941,335986,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,Sunrisers Hyderabad,bat,Kolkata Knight Riders,15.189175,13.275058,40.343036,28.996228,102.678496,99.015413,Kolkata,51.56

In [126]:
IPL_Final_Data = pd.merge(IPL_Final_Data,file4[['Team','HomeGround','WinningPercentage']],left_on='Team2',right_on='Team',how='left')
IPL_Final_Data

,ID,Team1,Team2,City,TossWinner,TossDecision,WinningTeam,Team1BattingAverage,Team2BattingAverage,Team1BowlingAverage,Team2BowlingAverage,Team1StrikeRate,Team2StrikeRate,HomeGround_x,WinningPercentage_x,Team,HomeGround_y,WinningPercentage_y
0,1312200,Rajasthan Royals,Gujarat Titans,Ahmedabad,Rajasthan Royals,bat,Gujarat Titans,15.483259,13.073874,18.708187,17.462245,114.139024,102.594500,Jaipur,50.26,Gujarat Titans,Ahmedabad,75.00
1,1312199,Royal Challengers Bangalore,Rajasthan Royals,Ahmedabad,Rajasthan Royals,field,Rajasthan Royals,17.775218,15.483259,32.692278,18.708187,114.000531,114.139024,Bangalore,48.65,Rajasthan Royals,Jaipur,50.26
2,1312198,Royal Challengers Bangalore,Lucknow Super Giants,Kolkata,Lucknow Super Giants,field,Royal Challengers Bangalore,17.775218,17.073565,32.692278,20.732313,114.000531,125.011089,Bangalore,48.65,Lucknow Super Giants,Lucknow,60.00
3,1312197,Rajasthan Royals,Gujarat Titans,Kolkata,Gujarat Titans,field,Gujarat Titans,15.483259,12.513268,18.708187,17.350909,114.139024,98.726028,Jaipur,50.26,Gujarat Titans,Ahmedabad,75.00
4,1304116,Sunrisers Hyderabad,Punjab Kings,Mumbai,Sunrisers Hyderabad,bat,Punjab Kings,13.963378,16.370308,29.160466,16.357071,107.851106,143.763969,Hyderabad,50.00,Punjab Kings,Punjab,45.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,335990,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,Rajasthan Royals,field,Rajasthan Royals,13.275058,13.718252,28.996228,25.987833,99.015413,101.871647,Hyderabad,50.00,Rajasthan Royals,Jaipur,50.26
938,335989,Chennai Super Kings,Mumbai Indians,Chennai,Mumbai Indians,field,Chennai Super Kings,12.219282,14.072797,19.462522,31.430482,105.212140,102.848265,Chennai,58.41,Mumbai Indians,Mumbai,56.70
939,335988,Sunrisers Hyderabad,Delhi Capitals,Hyderabad,Sunrisers Hyderabad,bat,Delhi Capitals,15.381031,10.775962,31.133237,23.123320,107.582916,101.354460,Hyderabad,50.00,Delhi Capitals,Delhi,45.94
940,335987,Rajasthan Royals,Punjab Kings,Jaipur,Punjab Kings,bat,Rajasthan Royals,12.928698,17.219262,21.043460,19.860622,97.513791,105.548630,Jaipur,50.26,Punjab Kings,Punjab,45.87
941,335986,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,Sunrisers Hyderabad,bat,Kolkata Knight Riders,15.189175,13.275058,40.343036,28.996228,102.678496,99.015413,Kolkata,51.56,Sunrisers Hyderabad,Hyderabad,50.00

In [127]:
IPL_Final_Data.drop(['Team'],axis=1,inplace=True)
IPL_Final_Data

,ID,Team1,Team2,City,TossWinner,TossDecision,WinningTeam,Team1BattingAverage,Team2BattingAverage,Team1BowlingAverage,Team2BowlingAverage,Team1StrikeRate,Team2StrikeRate,HomeGround_x,WinningPercentage_x,HomeGround_y,WinningPercentage_y
0,1312200,Rajasthan Royals,Gujarat Titans,Ahmedabad,Rajasthan Royals,bat,Gujarat Titans,15.483259,13.073874,18.708187,17.462245,114.139024,102.594500,Jaipur,50.26,Ahmedabad,75.00
1,1312199,Royal Challengers Bangalore,Rajasthan Royals,Ahmedabad,Rajasthan Royals,field,Rajasthan Royals,17.775218,15.483259,32.692278,18.708187,114.000531,114.139024,Bangalore,48.65,Jaipur,50.26
2,1312198,Royal Challengers Bangalore,Lucknow Super Giants,Kolkata,Lucknow Super Giants,field,Royal Challengers Bangalore,17.775218,17.073565,32.692278,20.732313,114.000531,125.011089,Bangalore,48.65,Lucknow,60.00
3,1312197,Rajasthan Royals,Gujarat Titans,Kolkata,Gujarat Titans,field,Gujarat Titans,15.483259,12.513268,18.708187,17.350909,114.139024,98.726028,Jaipur,50.26,Ahmedabad,75.00
4,1304116,Sunrisers Hyderabad,Punjab Kings,Mumbai,Sunrisers Hyderabad,bat,Punjab Kings,13.963378,16.370308,29.160466,16.357071,107.851106,143.763969,Hyderabad,50.00,Punjab,45.87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,335990,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,Rajasthan Royals,field,Rajasthan Royals,13.275058,13.718252,28.996228,25.987833,99.015413,101.871647,Hyderabad,50.00,Jaipur,50.26
938,335989,Chennai Super Kings,Mumbai Indians,Chennai,Mumbai Indians,field,Chennai Super Kings,12.219282,14.072797,19.462522,31.430482,105.212140,102.848265,Chennai,58.41,Mumbai,56.70
939,335988,Sunrisers Hyderabad,Delhi Capitals,Hyderabad,Sunrisers Hyderabad,bat,Delhi Capitals,15.381031,10.775962,31.133237,23.123320,107.582916,101.354460,Hyderabad,50.00,Delhi,45.94
940,335987,Rajasthan Royals,Punjab Kings,Jaipur,Punjab Kings,bat,Rajasthan Royals,12.928698,17.219262,21.043460,19.860622,97.513791,105.548630,Jaipur,50.26,Punjab,45.87
941,335986,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,Sunrisers Hyderabad,bat,Kolkata Knight Riders,15.189175,13.275058,40.343036,28.996228,102.678496,99.015413,Kolkata,51.56,Hyderabad,50.00

In [128]:
def result(row):
    return 1 if row['Team1'] == row['WinningTeam'] else 0

In [129]:
def T1HomeGround(row):
     return "Yes" if row['City'] == row['HomeGround_x'] else "No"

In [130]:
def T2HomeGround(row):
     return "Yes" if row['City'] == row['HomeGround_y'] else "No"

In [131]:
def battingfirst(row):
        if row['Team1'] == row['TossWinner']:
            if row['TossDecision'] == 'bat':
                return 1
            else:
                return 0
        elif row['Team2'] == row['TossWinner']:
            if row['TossDecision'] == 'bat':
                return 0
            else:
                return 1

In [132]:
IPL_Final_Data['Result'] = IPL_Final_Data.apply(result,axis=1)
IPL_Final_Data['Team1Home'] = IPL_Final_Data.apply(T1HomeGround,axis=1)
IPL_Final_Data['Team2Home'] = IPL_Final_Data.apply(T2HomeGround,axis=1)
IPL_Final_Data['BattingFirst'] = IPL_Final_Data.apply(battingfirst,axis=1)

In [133]:
IPL_Final_Data.drop(['HomeGround_x','HomeGround_y'],axis=1,inplace=True)
IPL_Final_Data

,ID,Team1,Team2,City,TossWinner,TossDecision,WinningTeam,Team1BattingAverage,Team2BattingAverage,Team1BowlingAverage,Team2BowlingAverage,Team1StrikeRate,Team2StrikeRate,WinningPercentage_x,WinningPercentage_y,Result,Team1Home,Team2Home,BattingFirst
0,1312200,Rajasthan Royals,Gujarat Titans,Ahmedabad,Rajasthan Royals,bat,Gujarat Titans,15.483259,13.073874,18.708187,17.462245,114.139024,102.594500,50.26,75.00,0,No,Yes,1
1,1312199,Royal Challengers Bangalore,Rajasthan Royals,Ahmedabad,Rajasthan Royals,field,Rajasthan Royals,17.775218,15.483259,32.692278,18.708187,114.000531,114.139024,48.65,50.26,0,No,No,1
2,1312198,Royal Challengers Bangalore,Lucknow Super Giants,Kolkata,Lucknow Super Giants,field,Royal Challengers Bangalore,17.775218,17.073565,32.692278,20.732313,114.000531,125.011089,48.65,60.00,1,No,No,1
3,1312197,Rajasthan Royals,Gujarat Titans,Kolkata,Gujarat Titans,field,Gujarat Titans,15.483259,12.513268,18.708187,17.350909,114.139024,98.726028,50.26,75.00,0,No,No,1
4,1304116,Sunrisers Hyderabad,Punjab Kings,Mumbai,Sunrisers Hyderabad,bat,Punjab Kings,13.963378,16.370308,29.160466,16.357071,107.851106,143.763969,50.00,45.87,0,No,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,335990,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,Rajasthan Royals,field,Rajasthan Royals,13.275058,13.718252,28.996228,25.987833,99.015413,101.871647,50.00,50.26,0,Yes,No,1
938,335989,Chennai Super Kings,Mumbai Indians,Chennai,Mumbai Indians,field,Chennai Super Kings,12.219282,14.072797,19.462522,31.430482,105.212140,102.848265,58.41,56.70,1,Yes,No,1
939,335988,Sunrisers Hyderabad,Delhi Capitals,Hyderabad,Sunrisers Hyderabad,bat,Delhi Capitals,15.381031,10.775962,31.133237,23.123320,107.582916,101.354460,50.00,45.94,0,Yes,No,1
940,335987,Rajasthan Royals,Punjab Kings,Jaipur,Punjab Kings,bat,Rajasthan Royals,12.928698,17.219262,21.043460,19.860622,97.513791,105.548630,50.26,45.87,1,Yes,No,0
941,335986,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,Sunrisers Hyderabad,bat,Kolkata Knight Riders,15.189175,13.275058,40.343036,28.996228,102.678496,99.015413,51.56,50.00,1,Yes,No,0

In [134]:
file5 = pd.read_csv("D:\IPL_WinPrediction\IPL_HeadToHead.csv")
file5

,Team1,Team2,Team1Wins,Team2Wins,Matches
0,Chennai Super Kings,Delhi Capitals,19,10,29
1,Chennai Super Kings,Gujarat Titans,2,3,5
2,Chennai Super Kings,Kolkata Knight Riders,18,10,29
3,Chennai Super Kings,Lucknow Super Giants,1,1,3
4,Chennai Super Kings,Mumbai Indians,16,20,36
...,...,...,...,...,...
127,Pune Warriors,Punjab Kings,1,4,5
128,Pune Warriors,Rajasthan Royals,0,3,3
129,Pune Warriors,Royal Challengers Bangalore,1,4,5
130,Pune Warriors,Sunrisers Hyderabad,3,2,5
131,Pune Warriors,Kochi Tuskers Kerala,1,0,1

In [135]:
IPL_Final_Data = pd.merge(IPL_Final_Data, file5, left_on=['Team1', 'Team2'], right_on=['Team1', 'Team2'])
IPL_Final_Data

,ID,Team1,Team2,City,TossWinner,TossDecision,WinningTeam,Team1BattingAverage,Team2BattingAverage,Team1BowlingAverage,...,Team2StrikeRate,WinningPercentage_x,WinningPercentage_y,Result,Team1Home,Team2Home,BattingFirst,Team1Wins,Team2Wins,Matches
0,1312200,Rajasthan Royals,Gujarat Titans,Ahmedabad,Rajasthan Royals,bat,Gujarat Titans,15.483259,13.073874,18.708187,...,102.594500,50.26,75.00,0,No,Yes,1,1,4,5
1,1312199,Royal Challengers Bangalore,Rajasthan Royals,Ahmedabad,Rajasthan Royals,field,Rajasthan Royals,17.775218,15.483259,32.692278,...,114.139024,48.65,50.26,0,No,No,1,15,12,30
2,1312198,Royal Challengers Bangalore,Lucknow Super Giants,Kolkata,Lucknow Super Giants,field,Royal Challengers Bangalore,17.775218,17.073565,32.692278,...,125.011089,48.65,60.00,1,No,No,1,3,1,4
3,1312197,Rajasthan Royals,Gujarat Titans,Kolkata,Gujarat Titans,field,Gujarat Titans,15.483259,12.513268,18.708187,...,98.726028,50.26,75.00,0,No,No,1,1,4,5
4,1304116,Sunrisers Hyderabad,Punjab Kings,Mumbai,Sunrisers Hyderabad,bat,Punjab Kings,13.963378,16.370308,29.160466,...,143.763969,50.00,45.87,0,No,No,1,14,7,21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,335990,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,Rajasthan Royals,field,Rajasthan Royals,13.275058,13.718252,28.996228,...,101.871647,50.00,50.26,0,Yes,No,1,9,9,18
938,335989,Chennai Super Kings,Mumbai Indians,Chennai,Mumbai Indians,field,Chennai Super Kings,12.219282,14.072797,19.462522,...,102.848265,58.41,56.70,1,Yes,No,1,16,20,36
939,335988,Sunrisers Hyderabad,Delhi Capitals,Hyderabad,Sunrisers Hyderabad,bat,Delhi Capitals,15.381031,10.775962,31.133237,...,101.354460,50.00,45.94,0,Yes,No,1,12,11,23
940,335987,Rajasthan Royals,Punjab Kings,Jaipur,Punjab Kings,bat,Rajasthan Royals,12.928698,17.219262,21.043460,...,105.548630,50.26,45.87,1,Yes,No,0,15,11,26
941,335986,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,Sunrisers Hyderabad,bat,Kolkata Knight Riders,15.189175,13.275058,40.343036,...,99.015413,51.56,50.00,1,Yes,No,0,16,9,25

In [136]:
def head_to_head(row):
    if row['Matches']!=0:
        row['Team1WinPercent'] = row['Team1Wins']/row['Matches']
        row['Team2WinPercent'] = row['Team2Wins']/row['Matches']
    else:
        row['Team1WinPercent'] = 0
        row['Team2WinPercent'] = 0
    return row

In [137]:
IPL_Final_Data = IPL_Final_Data.apply(head_to_head, axis=1)
IPL_Final_Data

,ID,Team1,Team2,City,TossWinner,TossDecision,WinningTeam,Team1BattingAverage,Team2BattingAverage,Team1BowlingAverage,...,WinningPercentage_y,Result,Team1Home,Team2Home,BattingFirst,Team1Wins,Team2Wins,Matches,Team1WinPercent,Team2WinPercent
0,1312200,Rajasthan Royals,Gujarat Titans,Ahmedabad,Rajasthan Royals,bat,Gujarat Titans,15.483259,13.073874,18.708187,...,75.00,0,No,Yes,1,1,4,5,0.200000,0.800000
1,1312199,Royal Challengers Bangalore,Rajasthan Royals,Ahmedabad,Rajasthan Royals,field,Rajasthan Royals,17.775218,15.483259,32.692278,...,50.26,0,No,No,1,15,12,30,0.500000,0.400000
2,1312198,Royal Challengers Bangalore,Lucknow Super Giants,Kolkata,Lucknow Super Giants,field,Royal Challengers Bangalore,17.775218,17.073565,32.692278,...,60.00,1,No,No,1,3,1,4,0.750000,0.250000
3,1312197,Rajasthan Royals,Gujarat Titans,Kolkata,Gujarat Titans,field,Gujarat Titans,15.483259,12.513268,18.708187,...,75.00,0,No,No,1,1,4,5,0.200000,0.800000
4,1304116,Sunrisers Hyderabad,Punjab Kings,Mumbai,Sunrisers Hyderabad,bat,Punjab Kings,13.963378,16.370308,29.160466,...,45.87,0,No,No,1,14,7,21,0.666667,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,335990,Sunrisers Hyderabad,Rajasthan Royals,Hyderabad,Rajasthan Royals,field,Rajasthan Royals,13.275058,13.718252,28.996228,...,50.26,0,Yes,No,1,9,9,18,0.500000,0.500000
938,335989,Chennai Super Kings,Mumbai Indians,Chennai,Mumbai Indians,field,Chennai Super Kings,12.219282,14.072797,19.462522,...,56.70,1,Yes,No,1,16,20,36,0.444444,0.555556
939,335988,Sunrisers Hyderabad,Delhi Capitals,Hyderabad,Sunrisers Hyderabad,bat,Delhi Capitals,15.381031,10.775962,31.133237,...,45.94,0,Yes,No,1,12,11,23,0.521739,0.478261
940,335987,Rajasthan Royals,Punjab Kings,Jaipur,Punjab Kings,bat,Rajasthan Royals,12.928698,17.219262,21.043460,...,45.87,1,Yes,No,0,15,11,26,0.576923,0.423077
941,335986,Kolkata Knight Riders,Sunrisers Hyderabad,Kolkata,Sunrisers Hyderabad,bat,Kolkata Knight Riders,15.189175,13.275058,40.343036,...,50.00,1,Yes,No,0,16,9,25,0.640000,0.360000

In [138]:
IPL_Final_Data.to_csv("D:\IPL_WinPrediction\IPL_Final_Data.csv",index=0)

In [139]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

encode_columns = ['Team1','Team2','City','TossWinner','TossDecision','WinningTeam','Team1Home','Team2Home','BattingFirst','Result']
                  
for column in encode_columns:
                  IPL_Final_Data[column] = label_encoder.fit_transform(IPL_Final_Data[column])

IPL_Final_Data

,ID,Team1,Team2,City,TossWinner,TossDecision,WinningTeam,Team1BattingAverage,Team2BattingAverage,Team1BowlingAverage,...,WinningPercentage_y,Result,Team1Home,Team2Home,BattingFirst,Team1Wins,Team2Wins,Matches,Team1WinPercent,Team2WinPercent
0,1312200,9,2,1,9,0,2,15.483259,13.073874,18.708187,...,75.00,0,0,1,1,1,4,5,0.200000,0.800000
1,1312199,10,9,1,9,1,9,17.775218,15.483259,32.692278,...,50.26,0,0,0,1,15,12,30,0.500000,0.400000
2,1312198,10,5,11,5,1,10,17.775218,17.073565,32.692278,...,60.00,1,0,0,1,3,1,4,0.750000,0.250000
3,1312197,9,2,11,2,1,2,15.483259,12.513268,18.708187,...,75.00,0,0,0,1,1,4,5,0.200000,0.800000
4,1304116,11,8,12,11,0,8,13.963378,16.370308,29.160466,...,45.87,0,0,0,1,14,7,21,0.666667,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
937,335990,11,9,9,9,1,9,13.275058,13.718252,28.996228,...,50.26,0,1,0,1,9,9,18,0.500000,0.500000
938,335989,0,6,5,6,1,0,12.219282,14.072797,19.462522,...,56.70,1,1,0,1,16,20,36,0.444444,0.555556
939,335988,11,1,9,11,0,1,15.381031,10.775962,31.133237,...,45.94,0,1,0,1,12,11,23,0.521739,0.478261
940,335987,9,8,10,8,0,9,12.928698,17.219262,21.043460,...,45.87,1,1,0,0,15,11,26,0.576923,0.423077
941,335986,4,11,11,11,0,4,15.189175,13.275058,40.343036,...,50.00,1,1,0,0,16,9,25,0.640000,0.360000

In [140]:
IPL_Final_Data.drop(['ID','Team1Wins','Team2Wins','Matches'],axis=1,inplace=True)

In [141]:
columns = IPL_Final_Data.columns.tolist()
if 'Result' in columns:
    columns.remove('Result')
columns

['Team1',
 'Team2',
 'City',
 'TossWinner',
 'TossDecision',
 'WinningTeam',
 'Team1BattingAverage',
 'Team2BattingAverage',
 'Team1BowlingAverage',
 'Team2BowlingAverage',
 'Team1StrikeRate',
 'Team2StrikeRate',
 'WinningPercentage_x',
 'WinningPercentage_y',
 'Team1Home',
 'Team2Home',
 'BattingFirst',
 'Team1WinPercent',
 'Team2WinPercent']

In [142]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
for column in columns:
                  IPL_Final_Data[column] = sc.fit_transform(IPL_Final_Data[[column]])
sc

StandardScaler()

In [143]:
X = IPL_Final_Data.drop(columns=['Team1Home','Team2Home','WinningTeam','Result'])
y = IPL_Final_Data['Result']

In [144]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.081,random_state=15)

In [145]:
from sklearn.linear_model import LinearRegression

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [146]:
#model = LinearRegression()
model = LogisticRegression()
#model = RandomForestClassifier()
#model = DecisionTreeClassifier(random_state=42)
#model = SVC(kernel='linear', C=1)
#model = XGBClassifier()
#model = GaussianNB()
#model = SVC(kernel='rbf', random_state=0)

In [147]:
model.fit(X_train,y_train)

LogisticRegression()

In [148]:
y_pred = model.predict(X_test)

In [149]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy_score(y_test,y_pred)

0.6103896103896104